const categoriesArray = [
  {
    name: "bread",
    hue: 40,
    products: {
      bread: 0,
      buns: 0,
      cake: 0,
      rye: 0,
      "whole mill": 0,
      garlic: 0,
    },
  },{
    name: "dairy",
    hue: 180,
    products: {
      milk: 0,
      butter: 0,
      cream: 0,
      "soured milk": 0,
      kefir: 0,
      yoghurt: 0,
      eggs: 0,
      "cottage cheese": 0,
      cheese: 0,
    },
  },{
    name: "cold drinks",
    hue: 190,
    products: {
      "sparkling water": 0,
      "still water": 0,
      "apple juice": 0,
      "grapes juice": 0,
      "grapefruit juice": 0,
      "orange juice": 0,
      "tomato juice": 0,
      "vegetable juice": 0,
      "other juice": 0,
      icetea: 0,
      tonic: 0,
      sprite: 0,
      cola: 0,
      fanta: 0,
    },
  },{
    name: "hot drinks",
    hue: 350,
    products: {
      coffee: 0,
      tea: 0,
      yerba: 0,
      combucha: 0,
    },
  },{
    name: "sweets and pastries",
    hue: 310,
    products: {
      chocolate: 0,
      cookies: 0,
      crackers: 0,
      nachos: 0,
      bars: 0,
      candies: 0,
    },
  },{
    name: "groats",
    hue: 30,
    products: {
      buckwheat: 0,
      millet: 0,
      groats: 0,
      "white rice": 0,
      "brown rice": 0,
      barley: 0,
    },
  },{
    name: "loose",
    hue: 240,
    products: {
      "wheat flour": 0,
      "oat flour": 0,
      "rye flour": 0,
      "rice flour": 0,
      sugar: 0,
      salt: 0,
      semolina: 0,
      "wholemeal flour": 0,
    },
  },{
    name: "spices",
    hue: 140,
    products: {
      pepper: 0,
      oregano: 0,
      allspice: 0,
      "bay leaf": 0,
      gyros: 0,
      kebab: 0,
      curry: 0,
      "herbs de Provence": 0,
      garlic: 0,
      ginger: 0,
      "sweet pepper": 0,
      "hot pepper": 0,
      ketchup: 0,
      horseradish: 0,
      mustard: 0,
      mayonnaise: 0,
    },
  },{
    name: "pasta",
    hue: 60,
    products: {
      macaroni: 0,
      penne: 0,
      spaghetti: 0,
      fusilli: 0,
      fettuccini: 0,
      rigatoni: 0,
      orzo: 0,
      lasagna: 0,
      papardelle: 0,
      farfalle: 0,
      squares: 0,
      shells: 0,
      wholewheat: 0,
    },
  },{
    name: "cold meat",
    hue: 360,
    products: {
      bacon: 0,
      ham: 0,
      sausage: 0,
      gammon: 0,
      brawn: 0,
      salami: 0,
      chorizo: 0,
      sirloin: 0,
      mackerel: 0,
      herring: 0,
      sprats: 0,
    },
  },{
    name: "fruits and nuts",
    hue: 20,
    products: {
      apple: 0,
      banana: 0,
      grape: 0,
      lemon: 0,
      lime: 0,
      orange: 0,
      pear: 0,
      plum: 0,
      almonds: 0,
      hazelnuts: 0,
      peanuts: 0,
      walnuts: 0,
    },
  },{
    name: "vegetables",
    hue: 100,
    products: {
      carrot: 0,
      potatoe: 0,
      parsley: 0,
      tomato: 0,
      pepper: 0,
      lettuce: 0,
      cabbage: 0,
      "soup greens": 0,
      cauliflower: 0,
      broccoli: 0,
      eggplant: 0,
      brussel: 0,
      bean: 0,
      asparagus: 0,
      garlic: 0,
      cucumber: 0,
      onion: 0,
      zucchini: 0,
    },
  },{
    name: "canned food",
    hue: 200,
    products: {
      corn: 0,
      peas: 0,
      olives: 0,
      chickpeas: 0,
      capers: 0,
      mix: 0,
      "red beans": 0,
      "white beans": 0,
    },
  },{
    name: "home chemistry",
    hue: 290,
    products: {
      deodorant: 0,
      shampoo: 0,
      "liquid soap": 0,
      "dishwashing liquid": 0,
      "cleaning milk": 0,
      toothpaste: 0,
      "washing powder": 0,
      "washing liquid": 0,
      "fabric softener": 0,
    },
  },{
    name: "utensils",
    hue: 230,
    products: {
      "wrapping paper": 0,
      "baking paper": 0,
      "cling foil": 0,
      "aluminium foil": 0,
      "coffee filters": 0,
      "toilet paper": 0,
      "paper towels": 0,
    },
  },{
    name: "medicines",
    hue: 110,
    products: {
      ibuprofen: 0,
      paracetamol: 0,
      "oxidized water": 0,
      "salicylic spirit": 0,
      aspirin: 0,
      tormentiol: 0,
      "benzydaminum spray": 0,
    },
  },{
    name: "alcohol",
    hue: 230,
    products: {
      beer: 0,
      wine: 0,
      vermouth: 0,
      gin: 0,
      rum: 0,
      whiskey: 0,
      vodka: 0
    }
  }
];

export { categoriesArray };
